services:
  calendar:
    image: postgres:17
    container_name: database
    environment:
      POSTGRES_USER: "calendar_user"
      POSTGRES_PASSWORD: "calendar_pass"
      POSTGRES_DB: "calendar"
    ports:
      - "9091:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    container_name: message-queue
    environment:
      RABBITMQ_DEFAULT_USER: "calendar_user"
      RABBITMQ_DEFAULT_PASS: "calendar_pass"
    ports:
      - "9092:5672"
      - "9093:15672"
    restart: unless-stopped

volumes:
  postgres_data:
