[app]
retries = 5 # Any int. Values <= 0 are treated as no retries

[logger]
level = "debug"                           # debug, info, warn, error
format = "text"                           # json, text
time_template = "02.01.2006 15:04:05.000" # Any valid time template. Default is "02.01.2006 15:04:05.000"
log_stream = "stdout"                     # stdout, stderr

[server]
shutdown_timeout = "3s"

[storage]
type = "asdad" # memory, sql

[storage.sql]
host = "localhost"
port = "5432"
user = "" # Better set with env. For the current structure use CALENDAR_STORAGE_SQL_USER
password = "" # Better set with env. For the current structure use CALENDAR_STORAGE_SQL_PASSWORD
dbname = "calendar"
timeout = "3s" # 0s means timeout will be disabled. Values lesser than seconds are also suppoted
driver = "postgres" # Currently suppoted drivers: postgres, postgresql

[storage.memory]
size = 10000 # 0 corresponds to the default value, which is currently 10_000


# TODO
# ...
