[app]
env = "dev"           # dev, prod
log_stream = "stdout" # stdout, stderr

[logger]
level = "info"  # debug, info, warn, error
format = "json" # json, text

[server]
shutdown_timeout = "3s"

[storage]
type = "in-memory" # in-memory, sql


# TODO
# ...
